# Use an official Python runtime as a parent image
FROM python:3.10.13-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Run the command to print "Hello, World!"
CMD ["python", "-c", "print('Hello, World!')"]

