name: cephal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.0.11
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - tmux=3.3a
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blessed==1.20.0
      - blosc2==2.0.0
      - cachetools==5.3.1
      - click==8.1.7
      - comm==0.1.4
      - contourpy==1.1.1
      - croniter==1.4.1
      - cycler==0.11.0
      - cython==3.0.2
      - dateutils==0.6.12
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepdiff==6.5.0
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - easydict==1.10
      - efficientnet-pytorch==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastapi==0.103.1
      - fastjsonschema==2.18.0
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.58.0
      - h11==0.14.0
      - h5py==3.8.0
      - huggingface-hub==0.17.2
      - imageio==2.31.3
      - inquirer==3.1.3
      - ipykernel==6.25.2
      - ipython==8.15.0
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.0
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==7.4.9
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==3.5.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning==2.0.9
      - lightning-cloud==0.5.38
      - lightning-utilities==0.9.0
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.1
      - msgpack==1.0.6
      - multidict==6.0.4
      - munch==4.0.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook==6.5.6
      - notebook-shim==0.2.3
      - numexpr==2.8.6
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opencv-python==4.6.0.66
      - ordered-set==4.1.0
      - overrides==7.4.0
      - packaging==23.1
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.3.0
      - platformdirs==3.10.0
      - pretrainedmodels==0.7.4
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pygments==2.16.1
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.9
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==24.0.1
      - ray==2.6.3
      - readchar==4.0.5
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.5.3
      - rpds-py==0.10.3
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-image==0.21.0
      - scipy==1.9.3
      - segmentation-models-pytorch==0.3.3
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - starlette==0.27.0
      - starsessions==1.3.0
      - tables==3.8.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - terminado==0.17.1
      - tifffile==2023.9.18
      - timm==0.9.2
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torchinfo==1.8.0
      - torchmetrics==1.2.0
      - torchview==0.2.6
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.10.0
      - uri-template==1.3.0
      - uvicorn==0.23.2
      - wandb==0.15.11
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - websockets==11.0.3
      - werkzeug==2.3.7
      - yarl==1.9.2
