RAW_DATA_DIRECTORY: "../data/raw"
INTERMEDIATE_DATA_DIRECTORY: "../data/intermediate"
PRIMARY_DATA_DIRECTORY: "../data/primary"

DATASET_1_RAW_ZIP_FILE_NAME: "radiography-20221212T190109Z-001.zip"
DATASET_1_INTERMEDIATE_DIR_NAME: "dataset_1"
DATASET_1_UNWANTED_JSON_FIELDS: ['imageData']

