RAW_DATA_DIRECTORY: "../../data/raw"
INTERMEDIATE_DATA_DIRECTORY: "../../data/intermediate"
PRIMARY_DATA_DIRECTORY: "../../data/primary"
ARTIFACTS_DATA_DIRECTORY: "../../artifacts"

# raw stage data config
DATASET_1_RAW_ZIP_FILE_NAME: "radiography-20221212T190109Z-001.zip"
DATASET_1_RAW_ZIP_NEW_ANNOT_FILE_NAME: "label_edited-20230122T143005Z-001.zip"
DATASET_1_INTERMEDIATE_DIR_NAME: "dataset_1"
DATASET_1_UNWANTED_JSON_FIELDS: ['imageData']

DATASET_3_RAW_RAR_FILE_NAME: "RawImage.rar"
DATASET_3_RAW_DIR_NAME_TEMP: "dataset_3_bmp"
DATASET_3_RAW_DIR_NAME: "dataset_3_raw_data"

# intermediate stage data config
UNWANTED_JSON_FIELDS: ['imageData', 'imagePath']

DATASET_1_INTERM_DIR_NAME: "dataset_1_interm_data-20230513T084705Z-001"
DATASET_1_INTERM_IMG_DIR_NAME: ["image"]
DATASET_1_INTERM_V_LANDMARKS_DIR_NAME: ["label"]
DATASET_1_INTERM_F_LANDMARKS_DIR_NAME: null

DATASET_2_INTERM_DIR_NAME: "dataset_2_interm_data-20230304T160421Z-001"
DATASET_2_INTERM_IMG_DIR_NAME: ["image"]
DATASET_2_INTERM_V_LANDMARKS_DIR_NAME: ["label"]
DATASET_2_INTERM_F_LANDMARKS_DIR_NAME: null

DATASET_3_INTERM_DIR_NAME: "dataset_3_interm_data-20230304T160433Z-001"
DATASET_3_INTERM_IMG_DIR_NAME: ["training/image", "test1/image", "test2/image"]
DATASET_3_INTERM_V_LANDMARKS_DIR_NAME: ["training/label", "test1/label", "test2/label"] 
DATASET_3_INTERM_F_LANDMARKS_DIR_NAME: "AnnotationsByMD/400_senior"

# primary stage data config
DATASET_1_EDGE_DETECT_SIGMA: 3
DATASET_2_EDGE_DETECT_SIGMA: 3
DATASET_3_EDGE_DETECT_SIGMA: 3

ARTIFACTS_GRAPHS_DIR_NAME: "sample_graphs"

# training: primary stage data config
METADATA_TABLE_NAME: 'metadata.hdf5'
DATASETS_TO_INCLUDE: ['dataset_2', 'dataset_3']
TARGET_IMAGE_SIZE: [256, 256] # change this when enough RAM is available